-- AlterTable
ALTER TABLE `LabRequest` MODIFY `status` ENUM('MENUNGGU_SAMPEL', 'SAMPEL_DITERIMA', 'VERIFIKASI', 'MENUNGGU_BILLING', 'MENUNGGU_PEMBAYARAN', 'LUNAS', 'ON_PROGRESS', 'SELESAI') NOT NULL DEFAULT 'MENUNGGU_SAMPEL';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `resetRequested` BOOLEAN NOT NULL DEFAULT false;
